name: 'main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Say hello
        run: echo " heelllo world"
      - name: BUILD DOCKER
        run:  docker buit -t devops-seminar .
      - name: DAGAT MGA GWAPO
        run: docker run -d -p 3000:80 devops-seminar
      - name: list docker containers
        run:  docker ps